CREATE TABLE posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE category (
  cate_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  cate_name VARCHAR(255) NOT NULL,
  PRIMARY KEY(cate_id)
);
